project:
  type: website
  resources:
    -  project/wood/appfiles/

execute:
  freeze: auto

website:
  title: "Luka"
  favicon: images/favicon.png
  site-url: https://www.luka-kovacevic.com
  description: "A data science and machine learning blog with the tidyverse at its {{< fa regular heart >}}"
  twitter-card: false
  open-graph: false
  navbar:
    logo: images/logo-light.png
    logo-alt: "A causal graph icon"
    title: false
    right:
      - text: about
        href: index.qmd
      # - text: blog  
      #   href: blog/index.qmd
      # - text: projects
      #   href: project/index.qmd
  page-footer:
    border: false
    left: "[Published with]{.quarto-pdf-footer} [Quarto](https://quarto.org/){.quarto-pdf-footer}<?quarto.version?>"
    right: "[© 2024 [Luka Kovačević](/about){.quarto-pdf-footer} | MIT License]{.quarto-pdf-footer}"

format:
  html:
    theme:
      light: [flatly, scss/light.scss]
      dark: [darkly, scss/dark.scss]
    css: scss/styles.css
    code-link: true
    link-external-icon: false
    link-external-newwindow: true
    smooth-scroll: true
    highlight-style: gruvbox
    df-print: kable
    comments:
      giscus:
        repo: luka-kovaceivc/luka-kovacevic.github.io
        category: "Comments"
        mapping: "pathname"
        reactions-enabled: true
        loading: lazy
        input-position: "bottom"
        theme:
          light: light_high_contrast
          dark: dark_dimmed

editor: visual

# filters:
#   - quarto-version.lua