baseURL = 'https://luka-kovacevic.com§/'
languageCode = 'en-us'
title = 'Luka Kovacevic'
theme = 'shibui'

[params]
  email = "luka.1kovacevic@gmail.com"
  comments = false
  showreadingtime = false

[params.author]
  name = "Luka Kovacevic"

[markup.tableOfContents]
  startLevel = 2
  endLevel = 2

[markup.goldmark.extensions.passthrough]
  enable = true

  [markup.goldmark.extensions.passthrough.delimiters]
    block = [['\[', '\]'], ['$$', '$$']]
    inline = [['\(', '\)'], ['$', '$']]
